cd..

echo on

CMD /C "echo. 2> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\lib\jquery-1.11.1.min.js > compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\lib\jmobile\1.4.5\jquery.mobile-1.4.5.min.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\lib\jquery.validate.min.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\lib\jpeg_encoder_basic.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\lib\base64-binary.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\lib\cropper.min.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\lib\aviary_editor.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\lib\vision.editor.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\cache\app-cache.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\db\db.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\db\file-storage.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\db\tbl-vis-settings.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\db\tbl-vis-gallery.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\dsl\ftp-util.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\ws\vision-ws.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\view\aboutus-view.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\view\settings-view.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\view\login-view.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\view\inspection-view.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\view\gallery-view.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\view\file-explorer-view.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\view\image-editor-view.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\view\preference_view.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\view\server-setting.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\app.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\sync\uploader.js >> compressor\vision_app.min.js"
CMD /C "java -jar compressor\yuicompressor-2.4.8.jar www\js\sync\downloader.js >> compressor\vision_app.min.js"